#!/usr/bin/env bash
# OPEN-MODEL-QWEN3 v3 (ACCEPTANCE-v3.md Section 5, PREPARED, NOT FROZEN): writes the declaration
# ../scoring/declarations/oq3-v3.decl.json from the v8 row shapes of the v2 declaration plus the
# v3 extra rows. Shell + jq only. Usage: gen-decl-oq3-v3.sh [OUT]   (default: the committed path)
# Row shapes: long = the T4 rows, edit = the T5 rows, identity = the R1 rows, negatives = N1 and N2
# (the v8 rows hard-code the ids N1, N2 and R1, so v3 keeps those ids; its goals are new).
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
V2=$HERE/../scoring/declarations/oq3-v2.decl.json
OUT=${1:-$HERE/../scoring/declarations/oq3-v3.decl.json}
TASKS=$HERE/tasks-oq3-v3.json
jq -n --slurpfile v2 "$V2" --slurpfile t "$TASKS" '
  def shape($from; $to): [$v2[0].rows[] | select(.row | startswith($from + "/"))
      | .row |= ($to + "/" + (.[($from | length) + 1:] | gsub($from + "-"; $to + "-")))];
  def extra($id; $names): [$names[] | {row: ($id + "/" + $id + "-" + .), role: "case", reps: 1, expected: "PASS", control: null, not_applicable: false}];
  ($t[0].tasks) as $tasks
  | ([$tasks[] | select(.kind == "long")  | .id as $i | shape("T4"; $i) + extra($i; ["SB", "F"] + (if ((.requirements // []) | length) > 0 then ["RQ"] else [] end) + ["D"])]
     + [$tasks[] | select(.kind == "edit") | .id as $i | shape("T5"; $i) + extra($i; ["SB", "D"])]
     + [$tasks[] | select(.kind == "identity") | .id as $i | shape("R1"; $i) + extra($i; ["SB", "D"])]
     + [$tasks[] | select(.kind == "negative-boundary") | .id as $i | shape("N1"; $i) + extra($i; ["D"])]
     + [$tasks[] | select(.kind == "negative-budget") | .id as $i | shape("N2"; $i) + extra($i; ["D", "R"])]
     | add) as $rows
  | {contract: "scoring-v5", campaign: "open-model-qwen3 v3",
     frozen_by: "docs/campaigns/open-model-qwen3/ACCEPTANCE-v3.md (Section 5); PREPARED, NOT FROZEN until that file says FROZEN",
     note: "v8 row shapes (115 rows of the v2 declaration, renamed to the v3 launch ids) plus the v3 extra rows SB, F, RQ, D (and N2-R). One repetition each, no controls, no NOT_APPLICABLE. Generated by gen-decl-oq3-v3.sh from tasks-oq3-v3.json.",
     rows: $rows}' >"$OUT"
