#!/usr/bin/env bash
# OPEN-MODEL-QWEN3 v4 (ACCEPTANCE-v4.md Section 4, PREPARED, NOT FROZEN): writes two declarations from the v8 row
# shapes of the v2 declaration plus the v4 extra rows. Shell + jq only. Usage:
#   gen-decl-oq3-v4.sh [QUAL_OUT [REGRESSION_OUT]]   (default: the committed paths)
# Qualification = tasks with group "qualification"; regression = group "regression". They are scored separately.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
V2=$HERE/../scoring/declarations/oq3-v2.decl.json
QOUT=${1:-$HERE/../scoring/declarations/oq3-v4.decl.json}
ROUT=${2:-$HERE/../scoring/declarations/oq3-v4-regression.decl.json}
TASKS=$HERE/tasks-oq3-v4.json
gen() {  # group out note
  jq -n --slurpfile v2 "$V2" --slurpfile t "$TASKS" --arg g "$1" --arg note "$3" --arg camp "$4" '
    def shape($from; $to): [$v2[0].rows[] | select(.row | startswith($from + "/"))
        | .row |= ($to + "/" + (.[($from | length) + 1:] | gsub($from + "-"; $to + "-")))];
    def extra($id; $names): [$names[] | {row: ($id + "/" + $id + "-" + .), role: "case", reps: 1, expected: "PASS", control: null, not_applicable: false}];
    ([$t[0].tasks[] | select(.group == $g)]) as $tasks
    | ([$tasks[] | select(.kind == "long") | .id as $i | (.requirements | length) as $n
         | shape("T4"; $i) + extra($i; ["SB", "F", "CUT"] + [range(1; $n + 1) | "RQ\(.)"] + (if .source != null then ["SRC"] else [] end) + ["D"])]
       + [$tasks[] | select(.kind == "edit") | .id as $i | shape("T5"; $i) + extra($i; ["SB", "CUT", "EO", "D"])]
       + [$tasks[] | select(.kind == "identity") | .id as $i | shape("R1"; $i) + extra($i; ["SB", "CUT", "D"])]
       + [$tasks[] | select(.kind == "negative-boundary") | .id as $i | shape("N1"; $i) + extra($i; ["D", "NC"])]
       + [$tasks[] | select(.kind == "negative-budget") | .id as $i | shape("N2"; $i) + extra($i; ["D", "NC", "R"])]
       | add) as $rows
    | {contract: "scoring-v5", campaign: $camp,
       frozen_by: "docs/campaigns/open-model-qwen3/ACCEPTANCE-v4.md (Section 4); PREPARED, NOT FROZEN until that file says FROZEN on main",
       note: $note, rows: $rows}' >"$2"
}
gen qualification "$QOUT" "v8 row shapes (the v2 declaration rows renamed to the v4 launch ids) plus the v4 extra rows (SB, F, CUT, RQ<k> one per declared requirement, SRC, EO, D, NC, N2-R). One repetition each, no controls, no NOT_APPLICABLE. This is the QUALIFICATION declaration. Generated by gen-decl-oq3-v4.sh from tasks-oq3-v4.json." "open-model-qwen3 v4 qualification"
gen regression "$ROUT" "REGRESSION declaration: reported, never part of the qualification verdict (ACCEPTANCE-v4 Section 6). Same row shapes as the qualification declaration. Generated by gen-decl-oq3-v4.sh from tasks-oq3-v4.json." "open-model-qwen3 v4 regression (reported only)"
