#!/usr/bin/env bash
# OPEN-MODEL-QWEN3 v5 (ACCEPTANCE-v5.md Section 4, DRAFT, NOT FROZEN): writes the qualification declaration from
# the v8 row shapes of the v2 declaration plus the v4 and v5 extra rows. Derived from gen-decl-oq3-v4.sh; shell + jq
# only. Usage:
#   gen-decl-oq3-v5.sh [OUT]   (default: the committed path)
# For N1 the v8 rows N1-B, N1-C and N1-H and the v4 row N1-D are not declared: they read a model attempt or the S3
# report, which a refusal before the model does not produce (gate G3). N1-NR, N1-NM, N1-RC and N1-RH replace them
# (ACCEPTANCE-v5 Section 3.3). The receipt still computes the three v8 rows; the scorer lists them as extras, outside the
# verdict. v5-rows.sh does not compute the v4 row N1-D.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
V2=$HERE/../scoring/declarations/oq3-v2.decl.json
OUT=${1:-$HERE/../scoring/declarations/oq3-v5.decl.json}
TASKS=$HERE/tasks-oq3-v5.json
# jq looks for a top-level include in the working directory before -L: read the row module from HERE only (the
# redirection to OUT is made by the outer shell, so a relative OUT still means the caller's directory).
(cd "$HERE" && jq -L "$HERE" -n --slurpfile v2 "$V2" --slurpfile t "$TASKS" '
  include "rows-oq3-v5";
  def shape($from; $to): [$v2[0].rows[] | select(.row | startswith($from + "/"))
      | .row |= ($to + "/" + (.[($from | length) + 1:] | gsub($from + "-"; $to + "-")))];
  def extra($id; $names): [$names[] | {row: ($id + "/" + $id + "-" + .), role: "case", reps: 1, expected: "PASS", control: null, not_applicable: false}];
  def product($committed): ["PRE", "DEC"] + (if $committed then ["GR"] else [] end) + ["OPR", "PIN", "MEAS"];
  def rq: [range(1; (.requirements | length) + 1) | "RQ\(.)"];
  ([$t[0].tasks[] | select(.group == "qualification")]) as $tasks
  | ([$tasks[] | select(.kind == "long") | .id as $i
       | shape("T4"; $i) + extra($i; ["SB", "F", "CUT"] + rq + (if .source != null then ["SRC"] else [] end) + ["D", "BE"] + product(true))]
     + [$tasks[] | select(.kind == "edit") | .id as $i
       | shape("T5"; $i) + extra($i; ["SB", "CUT", "EO"] + (if (v5_end_of_section_ids | index($i)) != null then ["EP"] else [] end) + ["D", "BE"] + product(true))]
     + [$tasks[] | select(.kind == "identity") | .id as $i | shape("R1"; $i) + extra($i; ["SB", "CUT"] + rq + ["D", "BE"] + product(true))]
     + [$tasks[] | select(.kind == "negative-boundary") | .id as $i
       | (shape("N1"; $i) | map(select(.row | test("-(B|C|H)$") | not)))
         + extra($i; ["NC", "BE", "NR", "NM", "RC", "RH", "OPR", "PIN", "MEAS"])]
     + [$tasks[] | select(.kind == "negative-budget") | .id as $i | shape("N2"; $i) + extra($i; ["D", "NC", "R", "BE"] + product(false))]
     | add) as $rows
  | {contract: "scoring-v5", campaign: "open-model-qwen3 v5 qualification",
     frozen_by: "docs/campaigns/open-model-qwen3/ACCEPTANCE-v5.md (Section 4); DRAFT, NOT FROZEN until that file says FROZEN on main",
     note: "v8 row shapes (the v2 declaration rows renamed to the v5 launch ids; for N1 without N1-B, N1-C and N1-H) plus the v4 extra rows (SB, F, CUT, RQ<k> one per declared requirement, SRC, EO, D, NC, BE, N2-R) and the v5 rows (PRE, DEC, GR, OPR, PIN, MEAS, E2-EP, N1-NR, N1-NM, N1-RC, N1-RH). One repetition each, no controls, no NOT_APPLICABLE. Generated by gen-decl-oq3-v5.sh from tasks-oq3-v5.json.",
     rows: $rows}') >"$OUT"
